version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: qcanvas_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qcanvas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qcanvas_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: qcanvas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qcanvas_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:community
    container_name: qcanvas_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - qcanvas_network

volumes:
  postgres_data:
  redis_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:


networks:
  qcanvas_network:
    driver: bridge
