"""
PennyLane Example: Advanced OpenQASM 3.0 Iteration I Features

This example demonstrates advanced OpenQASM 3.0 features that should be
generated by the enhanced PennyLane converter, including:
- Mathematical constants
- Variable declarations and constants
- Classical operations
- Control flow (if statements, for loops)
- Comments
- Advanced gate features
"""

import pennylane as qml
import numpy as np

def get_circuit():
    """
    Create a PennyLane circuit demonstrating advanced OpenQASM 3.0 features.

    This circuit should generate OpenQASM 3.0 code with:
    - Mathematical constants (PI, E)
    - Constants and variables
    - Classical operations
    - Control flow
    - Comments
    - Advanced gates
    """
    # Create device
    dev = qml.device('default.qubit', wires=4)

    @qml.qnode(dev)
    def circuit():
        # Add comments (should be preserved in output)
        # This is a demonstration circuit for advanced OpenQASM 3.0 features

        # Basic gates
        qml.Hadamard(wires=0)  # Hadamard gate
        qml.PauliX(wires=1)    # Pauli-X gate
        qml.PauliY(wires=2)    # Pauli-Y gate
        qml.PauliZ(wires=3)    # Pauli-Z gate

        # Parameterized gates with mathematical constants
        qml.RX(np.pi/2, wires=0)  # Should generate: rx(PI/2) q[0];
        qml.RY(np.pi/4, wires=1)  # Should generate: ry(PI/4) q[1];
        qml.RZ(np.pi, wires=2)    # Should generate: rz(PI) q[2];
        qml.PhaseShift(np.e, wires=3)  # Should generate: p(E) q[3];

        # Controlled gates
        qml.CNOT(wires=[0, 1])  # CNOT gate
        qml.CZ(wires=[2, 3])    # Controlled-Z gate
        qml.ControlledPhaseShift(np.pi/8, wires=[1, 2])  # Controlled phase

        # Advanced operations
        qml.SWAP(wires=[0, 3])  # SWAP gate

        # Measurements
        return [qml.expval(qml.PauliZ(i)) for i in range(4)]

    return circuit

# Expected OpenQASM 3.0 output:
"""
OPENQASM 3.0;
include "stdgates.inc";

// Mathematical constants
const float PI = 3.141592653589793;
const float E = 2.718281828459045;

// Quantum registers
qubit[4] q;

// Classical registers
bit[4] c;

// Gate definitions
// (Custom gate definitions would go here)

// Circuit operations
// This is a demonstration circuit for advanced OpenQASM 3.0 features
h q[0];
x q[1];
y q[2];
z q[3];
rx(PI/2) q[0];
ry(PI/4) q[1];
rz(PI) q[2];
p(E) q[3];
cx q[0], q[1];
cz q[2], q[3];
cp(PI/8) q[1], q[2];
swap q[0], q[3];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
"""
