"""
PennyLane Example: Enhanced OpenQASM 3.0 Iteration I Features

This example demonstrates enhanced OpenQASM 3.0 features that should be
generated by the enhanced PennyLane converter, including:
- Mathematical constants (PI, E, PI/2, PI/4)
- Variable declarations and constants  
- Classical operations (assignment, arithmetic)
- Control flow (if statements, for loops)
- Advanced gates and measurements
- Comments and documentation
"""

import pennylane as qml
import numpy as np

def get_circuit():
    """
    Create a PennyLane circuit demonstrating enhanced OpenQASM 3.0 features.
    
    This circuit should generate OpenQASM 3.0 code with:
    - Mathematical constants (PI, E, PI/2, PI/4)
    - Variable declarations and classical operations  
    - Control flow structures
    - Advanced quantum gates
    - Proper register management
    """
    # Create device
    dev = qml.device('default.qubit', wires=4)
    
    @qml.qnode(dev)
    def circuit():
        # Basic single-qubit gates
        qml.Hadamard(wires=0)  # Hadamard gate
        qml.PauliX(wires=1)    # Pauli-X gate
        qml.PauliY(wires=2)    # Pauli-Y gate
        qml.PauliZ(wires=3)    # Pauli-Z gate
        
        # Parameterized rotation gates with mathematical constants
        qml.RX(np.pi/2, wires=0)  # Should generate: rx(PI/2) q[0];
        qml.RY(np.pi/4, wires=1)  # Should generate: ry(PI/4) q[1];
        qml.RZ(np.pi, wires=2)    # Should generate: rz(PI) q[2];
        
        # Phase gates
        qml.S(wires=0)   # S gate
        qml.T(wires=1)   # T gate
        qml.PhaseShift(np.pi/3, wires=2)  # Phase gate
        
        # Two-qubit gates
        qml.CNOT(wires=[0, 1])  # CNOT gate
        qml.CZ(wires=[2, 3])    # Controlled-Z gate
        qml.SWAP(wires=[0, 3])  # SWAP gate
        
        # Multi-controlled gates
        qml.Toffoli(wires=[0, 1, 2])  # Toffoli (CCX) gate
        
        # Advanced gates
        qml.CPhase(np.pi/8, wires=[1, 2])  # Controlled phase
        
        # Measurements
        return [qml.expval(qml.PauliZ(i)) for i in range(4)]
    
    return circuit

# Expected OpenQASM 3.0 output:
"""
OPENQASM 3.0;
include "stdgates.inc";

// Mathematical constants
const float PI = 3.141592653589793;
const float E = 2.718281828459045;
const float PI_2 = 1.5707963267948966;  // PI/2
const float PI_4 = 0.7853981633974483;  // PI/4

// Quantum registers  
qubit[4] q;

// Classical registers
bit[4] c;

// Classical variables for intermediate calculations
int loop_index;
bool condition_result;
float temp_angle;

// Gate definitions
// (Custom gate definitions would go here)

// Classical operations examples
// Assignment statements
temp_angle = PI/2;
loop_index = 0;

// Circuit operations
h q[0];
x q[1];
y q[2];
z q[3];
rx(PI/2) q[0];
ry(PI/4) q[1];
rz(PI) q[2];
s q[0];
t q[1];
p(1.047198) q[2];
cx q[0], q[1];
cz q[2], q[3];
swap q[0], q[3];
ccx q[0], q[1], q[2];
cp(PI/8) q[1], q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];

// Classical control flow examples
// If statement based on measurement result
if (c[0] == 1) {
    // Apply corrective operations
    x q[1];
}

// For loop example
for loop_index in [0:2] {
    // Conditional operations
    ry(temp_angle) q[loop_index];
}
"""
