"""Add bio field to User

Revision ID: 4ada97e0e3b4
Revises: b2c3d4e5f6a7
Create Date: 2026-03-10 15:24:12.693249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ada97e0e3b4'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute('ALTER TABLE files DROP CONSTRAINT IF EXISTS fk_files_user_id_users')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    op.alter_column('gamification_activities', 'activity_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Indexes on gamification_activities were already dropped in a previous migration.
    # Use IF EXISTS to avoid errors when running on databases where they are missing.
    op.execute('DROP INDEX IF EXISTS "idx_activity_created";')
    op.execute('DROP INDEX IF EXISTS "idx_activity_type";')
    op.execute('DROP INDEX IF EXISTS "idx_activity_user_created";')
    op.alter_column('user_achievements', 'progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # This index may already have been dropped by an earlier migration; make this safe.
    op.execute('DROP INDEX IF EXISTS "idx_user_achievement_unique";')
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.create_index(op.f('idx_user_achievement_unique'), 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.alter_column('user_achievements', 'progress',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_activity_user_created'), 'gamification_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_activity_type'), 'gamification_activities', ['activity_type'], unique=False)
    op.create_index(op.f('idx_activity_created'), 'gamification_activities', ['created_at'], unique=False)
    op.alter_column('gamification_activities', 'activity_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.execute('ALTER TABLE files DROP CONSTRAINT IF EXISTS fk_files_user_id_users')
    op.create_foreign_key(op.f('fk_files_user_id_users'), 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('files', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('achievements', 'criteria',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
