"""Add SharedSnippet model

Revision ID: 4fd87f233920
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 12:27:49.466593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fd87f233920'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    quantumframework_enum = postgresql.ENUM(
        'CIRQ',
        'QISKIT',
        'PENNYLANE',
        name='quantumframework',
        create_type=False,
    )

    op.create_table('shared_snippets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', quantumframework_enum, nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gamification_activities', sa.Column('activity_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_activity_created'), table_name='gamification_activities')
    op.drop_index(op.f('idx_activity_type'), table_name='gamification_activities')
    op.drop_index(op.f('idx_activity_user_created'), table_name='gamification_activities')
    op.drop_column('gamification_activities', 'metadata')
    op.drop_index(op.f('idx_user_achievement_unique'), table_name='user_achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_achievement_unique'), 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.add_column('gamification_activities', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_activity_user_created'), 'gamification_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_activity_type'), 'gamification_activities', ['activity_type'], unique=False)
    op.create_index(op.f('idx_activity_created'), 'gamification_activities', ['created_at'], unique=False)
    op.drop_column('gamification_activities', 'activity_metadata')
    op.drop_table('shared_snippets')
    # ### end Alembic commands ###
