"""add_sharedsnippet_model

Revision ID: 82f94e6c24fb
Revises: 4fd87f233920
Create Date: 2026-03-10 13:41:43.779213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82f94e6c24fb'
down_revision: Union[str, Sequence[str], None] = '4fd87f233920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_snippets', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('shared_snippets', 'framework',
               existing_type=postgresql.ENUM('CIRQ', 'QISKIT', 'PENNYLANE', name='quantumframework'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('shared_snippets', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('shared_snippets', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shared_snippets', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_snippets', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shared_snippets', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shared_snippets', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('shared_snippets', 'framework',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CIRQ', 'QISKIT', 'PENNYLANE', name='quantumframework'),
               existing_nullable=False)
    op.alter_column('shared_snippets', 'id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
