"""Update user roles to USER ADMIN DEMO

Revision ID: 83149d586e8a
Revises: 0ee5ac065b13
Create Date: 2025-12-02 01:02:08.190467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83149d586e8a'
down_revision: Union[str, Sequence[str], None] = '0ee5ac065b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
