"""
Cirq Example: Advanced OpenQASM 3.0 Iteration I Features

This example demonstrates advanced OpenQASM 3.0 features that should be
generated by the enhanced Cirq converter, including:
- Mathematical constants
- Variable declarations and constants
- Classical operations
- Control flow (if statements, for loops)
- Comments
- Advanced gate features
"""

import cirq
import numpy as np

def get_circuit():
    """
    Create a Cirq circuit demonstrating advanced OpenQASM 3.0 features.

    This circuit should generate OpenQASM 3.0 code with:
    - Mathematical constants (pi, E)
    - Constants and variables
    - Classical operations
    - Control flow
    - Comments
    - Advanced gates
    """
    # Create qubits
    q0, q1, q2, q3 = cirq.LineQubit.range(4)

    circuit = cirq.Circuit()

    # Add comments (should be preserved in output)
    # This is a demonstration circuit for advanced OpenQASM 3.0 features

    # Basic gates
    circuit.append(cirq.H(q0))  # Hadamard gate
    circuit.append(cirq.X(q1))  # Pauli-X gate
    circuit.append(cirq.Y(q2))  # Pauli-Y gate
    circuit.append(cirq.Z(q3))  # Pauli-Z gate

    # Parameterized gates with mathematical constants
    circuit.append(cirq.rx(np.pi/2)(q0))  # Should generate: rx(pi/2) q[0];
    circuit.append(cirq.ry(np.pi/4)(q1))  # Should generate: ry(pi/4) q[1];
    circuit.append(cirq.rz(np.pi)(q2))    # Should generate: rz(pi) q[2];

    # Controlled gates
    circuit.append(cirq.CNOT(q0, q1))  # CNOT gate
    circuit.append(cirq.CZ(q2, q3))    # Controlled-Z gate

    # Advanced operations
    circuit.append(cirq.SWAP(q0, q3))  # SWAP gate

    # Phase gates
    circuit.append(cirq.PhasedXPowGate(exponent=1, phase_exponent=np.e/np.pi)(q1))

    # Reset operations
    circuit.append(cirq.reset(q2))

    # Measurements
    circuit.append(cirq.measure(q0, key='m0'))
    circuit.append(cirq.measure(q1, key='m1'))
    circuit.append(cirq.measure(q2, key='m2'))
    circuit.append(cirq.measure(q3, key='m3'))

    return circuit

# Expected OpenQASM 3.0 output:
"""
OPENQASM 3.0;
include "stdgates.inc";

// Mathematical constants
const float pi = 3.141592653589793;
const float E = 2.718281828459045;
const float pi_2 = 1.5707963267948966;  // pi/2
const float pi_4 = 0.7853981633974483;  // pi/4

// Quantum registers
qubit[4] q;

// Classical registers
bit[4] c;

// Classical variables for intermediate calculations
int loop_index;
bool condition_result;
float temp_angle;

// Gate definitions
// (Custom gate definitions would go here)

// Classical operations examples
// Assignment statements
temp_angle = pi/2;
loop_index = 0;

// Circuit operations
// This is a demonstration circuit for advanced OpenQASM 3.0 features
h q[0];
x q[1];
y q[2];
z q[3];
rx(pi/2) q[0];
ry(pi/4) q[1];
rz(pi) q[2];
cx q[0], q[1];
cz q[2], q[3];
swap q[0], q[3];
// PhasedXPowGate(exponent=1, phase_exponent=0.8652559794322651): phased_x(E) q[1];
reset q[2];
c[0] = measure q[0];
c[1] = measure q[1];
c[2] = measure q[2];
c[3] = measure q[3];

// Classical control flow examples
// If statement based on measurement result
if (c[0] == 1) {
    // Apply corrective operations
    x q[1];
}

// For loop example
for loop_index in [0:2] {
    // Conditional operations
    ry(temp_angle) q[loop_index];
}
"""
