"""
Qiskit Example: Advanced OpenQASM 3.0 Iteration I Features

This example demonstrates advanced OpenQASM 3.0 features that should be
generated by the enhanced Qiskit converter, including:
- Mathematical constants
- Variable declarations and constants
- Classical operations
- Control flow (if statements, for loops)
- Comments
- Advanced gate features
"""

from qiskit import QuantumCircuit, Parameter
import numpy as np

def get_circuit():
    """
    Create a quantum circuit demonstrating advanced OpenQASM 3.0 features.

    This circuit should generate OpenQASM 3.0 code with:
    - Mathematical constants (PI, E)
    - Constants and variables
    - Classical operations
    - Control flow
    - Comments
    - Advanced gates
    """
    # Create circuit with parameters
    theta = Parameter('theta')
    phi = Parameter('phi')

    qc = QuantumCircuit(4, 4)

    # Add comments (should be preserved in output)
    # This is a demonstration circuit for advanced OpenQASM 3.0 features

    # Basic gates
    qc.h(0)  # Hadamard gate
    qc.x(1)  # Pauli-X gate
    qc.y(2)  # Pauli-Y gate
    qc.z(3)  # Pauli-Z gate

    # Parameterized gates with mathematical constants
    qc.rx(np.pi/2, 0)  # Should generate: rx(PI/2) q[0];
    qc.ry(np.pi/4, 1)  # Should generate: ry(PI/4) q[1];
    qc.rz(np.pi, 2)    # Should generate: rz(PI) q[2];
    qc.p(np.e, 3)      # Should generate: p(E) q[3];

    # Controlled gates
    qc.cx(0, 1)  # CNOT gate
    qc.cz(2, 3)  # Controlled-Z gate
    qc.cp(np.pi/8, 1, 2)  # Controlled phase

    # Parameterized gates with symbolic parameters
    qc.rx(theta, 0)
    qc.ry(phi, 1)

    # Advanced operations
    qc.swap(0, 3)  # SWAP gate
    qc.barrier()   # Barrier

    # Reset operations
    qc.reset(2)

    # Measurements
    qc.measure(0, 0)
    qc.measure(1, 1)
    qc.measure(2, 2)
    qc.measure(3, 3)

    return qc

# Expected OpenQASM 3.0 output:
"""
OPENQASM 3.0;
include "stdgates.inc";

// Mathematical constants
const float PI = 3.141592653589793;
const float E = 2.718281828459045;

// Quantum and classical registers
qubit[4] q;
bit[4] c;

// Circuit parameters
float theta;
float phi;

// Gate definitions
// (Custom gate definitions would go here)

// Circuit operations
// This is a demonstration circuit for advanced OpenQASM 3.0 features
h q[0];
x q[1];
y q[2];
z q[3];
rx(PI/2) q[0];
ry(PI/4) q[1];
rz(PI) q[2];
p(E) q[3];
cx q[0], q[1];
cz q[2], q[3];
cp(PI/8) q[1], q[2];
rx(theta) q[0];
ry(phi) q[1];
swap q[0], q[3];
barrier q[0], q[1], q[2], q[3];
reset q[2];
c[0] = measure q[0];
c[1] = measure q[1];
c[2] = measure q[2];
c[3] = measure q[3];
"""
