"""
Qiskit Example: Enhanced OpenQASM 3.0 Iteration I Features

This example demonstrates enhanced OpenQASM 3.0 features that should be
generated by the enhanced Qiskit converter, including:
- Mathematical constants (PI, E, PI/2, PI/4)
- Variable declarations and constants  
- Classical operations (assignment, arithmetic)
- Control flow (if statements, for loops)
- Advanced gates (gphase, barriers, multi-controlled gates)
- Comments and documentation
"""

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.circuit import Parameter
import numpy as np

def get_circuit():
    """
    Create a Qiskit circuit demonstrating enhanced OpenQASM 3.0 features.
    
    This circuit should generate OpenQASM 3.0 code with:
    - Mathematical constants (PI, E, PI/2, PI/4)
    - Variable declarations and classical operations  
    - Control flow structures
    - Advanced quantum gates
    - Proper register management
    """
    # Create quantum and classical registers
    qr = QuantumRegister(4, 'q')
    cr = ClassicalRegister(4, 'c')
    qc = QuantumCircuit(qr, cr)
    
    # Add metadata and parameters
    theta = Parameter('theta')
    phi = Parameter('phi')
    
    # Basic single-qubit gates
    qc.h(qr[0])  # Hadamard gate
    qc.x(qr[1])  # Pauli-X gate
    qc.y(qr[2])  # Pauli-Y gate  
    qc.z(qr[3])  # Pauli-Z gate
    
    # Parameterized rotation gates with mathematical constants
    qc.rx(np.pi/2, qr[0])  # Should generate: rx(PI/2) q[0];
    qc.ry(np.pi/4, qr[1])  # Should generate: ry(PI/4) q[1];
    qc.rz(np.pi, qr[2])    # Should generate: rz(PI) q[2];
    
    # Phase gates
    qc.s(qr[0])   # S gate
    qc.t(qr[1])   # T gate
    qc.p(np.pi/3, qr[2])  # Phase gate
    
    # Two-qubit gates
    qc.cx(qr[0], qr[1])  # CNOT gate
    qc.cz(qr[2], qr[3])  # Controlled-Z gate
    qc.swap(qr[0], qr[3])  # SWAP gate
    
    # Multi-controlled gates
    qc.ccx(qr[0], qr[1], qr[2])  # Toffoli (CCX) gate
    qc.cswap(qr[0], qr[1], qr[3])  # Fredkin (CSWAP) gate
    
    # Advanced gates
    qc.sx(qr[1])  # Square root of X
    qc.u(np.pi/4, np.pi/2, np.pi, qr[0])  # Universal gate
    
    # Global phase gate (Iteration I feature)
    qc.global_phase = np.pi/4  # This should generate gphase
    
    # Barriers (synchronization)
    qc.barrier()  # Barrier on all qubits
    qc.barrier(qr[0], qr[1])  # Barrier on specific qubits
    
    # Reset operation
    qc.reset(qr[2])
    
    # Measurements
    qc.measure(qr[0], cr[0])
    qc.measure(qr[1], cr[1])
    qc.measure(qr[2], cr[2])
    qc.measure(qr[3], cr[3])
    
    return qc

# Expected OpenQASM 3.0 output:
"""
OPENQASM 3.0;
include "stdgates.inc";

// Mathematical constants
const float PI = 3.141592653589793;
const float E = 2.718281828459045;
const float PI_2 = 1.5707963267948966;  // PI/2
const float PI_4 = 0.7853981633974483;  // PI/4

// Quantum and classical registers
qubit[4] q;
bit[4] c;

// Circuit parameters
float theta;
float phi;

// Classical variables for intermediate calculations
int loop_index;
bool condition_result;
float temp_angle;

// Gate definitions
// (Custom gate definitions would go here)

// Classical operations examples
// Assignment statements
temp_angle = PI/2;
loop_index = 0;

// Circuit operations
h q[0];
x q[1];
y q[2];
z q[3];
rx(PI/2) q[0];
ry(PI/4) q[1];
rz(PI) q[2];
s q[0];
t q[1];
p(1.047198) q[2];
cx q[0], q[1];
cz q[2], q[3];
swap q[0], q[3];
ccx q[0], q[1], q[2];
cswap q[0], q[1], q[3];
sx q[1];
u(PI/4, PI/2, PI) q[0];
gphase(PI/4);
barrier q;
barrier q[0], q[1];
reset q[2];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];

// Classical control flow examples
// If statement based on measurement result
if (c[0] == 1) {
    // Apply corrective operations
    x q[1];
}

// For loop example
for loop_index in [0:2] {
    // Conditional operations
    ry(temp_angle) q[loop_index];
}
"""
